# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-RHash
version:      0.02
version_from: RHash.pm
installdirs:  site
requires:
    Hash::Util:                    0.05
    NEXT:                          0.60

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
